### ISSUE TITLE
Max number of thread config

### ISSUE THREAD

**Issue by briankudera** [andreujuanc/TakoDeploy#7]
(AWESOME TOOL!)

Configuring the max number of threads to run consecutively would be a perfect addition.

**Comment by andreujuanc** [comment]
Hi, thank you!! Hope you find it useful.

What would you try to accomplish with this? Like run each query one by one?(just curious) 

Cheers!

**Comment by briankudera** [comment]
I was looking at running a hefty update statement against a Dada source
that had about 40 databases after filtering. Hitting all 40 at once may
take the box down so if I could set number of threads to, 8 for example,
I'd feel a bit better about running such command.

**Comment by andreujuanc** [comment]
Ah I see. Then it's not the number of threads. But need some mechanism to "queue" the tasks.
because even if it runs on single thread the tasks are all started.

Would a "switch" near the deploy button be good? Instead of a general setting, something more focus on the current document.

**Comment by briankudera** [comment]
Yes exactly! Yes that sounds appropriate. Definitely a per deploy setting.

**Comment by andreujuanc** [comment]
Ok!! Gonna see if I can do it this weekend.  Gonna have to make some changes to the core probably.

**Comment by andreujuanc** [comment]
@briankudera very rough, but done. 
I added a switch under the deploy button, turn it on before deploying. Let me know if this works for you.

Cheers!

**Comment by briankudera** [comment]
Very fancy! For a first pass, this gets the job done!

It would still be nice to assign a max number of "threads" (or, parallel tasks to be running at once) that we'd like to run. For example, if I have 4 CPU's, max concurrent executions I would run would be 4.

But, running them 1 at a time, while slower, is just as safe, if not safer! 👍
